export type GlossaryCategory = "acronym" | "area" | "marking" | "concept" | "procedure";

export interface GlossaryEntry {
  id: string;
  term: string;
  fullForm?: string;   // only for acronyms
  definition: string;
  category: GlossaryCategory;
  color: string;       // hardcoded tailwind pill classes — never change for memorization
}

export const GLOSSARY: GlossaryEntry[] = [
  // ── ACRONYMS ──────────────────────────────────────────────────────────────
  {
    id: "gl-adc",
    term: "ADC",
    fullForm: "Airside Driving Certificate",
    definition: "Abilitazione personale e non cedibile per la guida di veicoli in Airside. Validità 4 anni. Richiede recurrent training ogni 24 mesi e attestato Airside Safety Modulo 2 valido.",
    category: "acronym",
    color: "bg-blue-900/60 text-blue-300",
  },
  {
    id: "gl-adc-a",
    term: "ADC-A",
    fullForm: "Airside Driving Certificate tipo A",
    definition: "Abilita la guida su piazzali (Apron), viabilità veicolare in Airside e strada perimetrale (soggetti autorizzati). Non include l'Area di Manovra.",
    category: "acronym",
    color: "bg-blue-900/60 text-blue-300",
  },
  {
    id: "gl-adc-m",
    term: "ADC-M",
    fullForm: "Airside Driving Certificate tipo M",
    definition: "Include tutte le aree dell'ADC-A più l'Area di Manovra (piste e taxiway principali). Richiede radio UHF in contatto con la TWR.",
    category: "acronym",
    color: "bg-indigo-900/60 text-indigo-300",
  },
  {
    id: "gl-tia",
    term: "TIA",
    fullForm: "Tesserino Ingresso Aeroportuale",
    definition: "Permesso di accesso in Airside. Prerequisito obbligatorio per ottenere l'ADC. Deve essere sempre ben esposto (banda verde o rossa; banda azzurro 4 per cargo FCO).",
    category: "acronym",
    color: "bg-violet-900/60 text-violet-300",
  },
  {
    id: "gl-fod",
    term: "FOD",
    fullForm: "Foreign Object Damage / Debris",
    definition: "Qualunque oggetto estraneo che potrebbe causare danni a un aeromobile o ai suoi motori. Va raccolto e segnalato immediatamente. Un bullone sul piazzale può distruggere un motore.",
    category: "acronym",
    color: "bg-rose-900/60 text-rose-300",
  },
  {
    id: "gl-era",
    term: "ERA",
    fullForm: "Equipment Restriction Area",
    definition: "Zona ad accesso limitato per i mezzi di rampa, nelle immediate vicinanze dell'aeromobile. Visibile sullo schema di piazzola come area protetta attorno alla fusoliera.",
    category: "acronym",
    color: "bg-orange-900/60 text-orange-300",
  },
  {
    id: "gl-esa",
    term: "ESA",
    fullForm: "Equipment Service Area",
    definition: "Area di attesa per i mezzi di rampa prima di avanzare verso l'aeromobile. Si trova tra la barra di allineamento e la stop line della piazzola.",
    category: "acronym",
    color: "bg-amber-900/60 text-amber-300",
  },
  {
    id: "gl-erl",
    term: "ERL",
    fullForm: "Equipment Restriction Line",
    definition: "Linea tratteggiata rossa che delimita l'ERA. I mezzi non possono varcarla senza specifica autorizzazione operativa.",
    category: "acronym",
    color: "bg-red-900/60 text-red-300",
  },
  {
    id: "gl-abl",
    term: "ABL",
    fullForm: "Apron Border Line",
    definition: "Linea rossa continua che separa la viabilità veicolare dall'area riservata agli aeromobili. Non deve mai essere oltrepassata dai veicoli senza autorizzazione.",
    category: "acronym",
    color: "bg-red-800/60 text-red-300",
  },
  {
    id: "gl-ade",
    term: "ADE",
    fullForm: "Airside Driving Expert",
    definition: "Istruttore qualificato di tipo A (Gruppo ADR o da ADR qualificato) che supervisiona l'addestramento pratico per l'ADC-A.",
    category: "acronym",
    color: "bg-purple-900/60 text-purple-300",
  },
  {
    id: "gl-cea",
    term: "CEA",
    fullForm: "Coordinamento Emergenze Airside",
    definition: "Centro di coordinamento delle emergenze di ADR. Tel. 06 65953022. Da contattare immediatamente per qualsiasi inconveniente, incidente o sversamento di idrocarburi.",
    category: "acronym",
    color: "bg-red-950/80 text-red-300",
  },
  {
    id: "gl-gsr",
    term: "GSR",
    fullForm: "Ground Safety Report",
    definition: "Modulo da compilare per segnalare incidenti tra mezzi e/o comportamenti o condizioni pericolose in Airside. Strumento fondamentale di safety reporting (da compilare anche per i «quasi-incidenti»).",
    category: "acronym",
    color: "bg-pink-900/60 text-pink-300",
  },
  {
    id: "gl-lvp",
    term: "LVP",
    fullForm: "Low Visibility Procedures",
    definition: "Procedure attivate in condizioni di bassa visibilità. Impongono: fari anabbaglianti accesi, velocità ridotta, attenzione speciale agli attraversamenti taxiway. Le scorte a veicoli non urgenti vengono sospese.",
    category: "acronym",
    color: "bg-slate-700/80 text-slate-300",
  },
  {
    id: "gl-npa",
    term: "NPA",
    fullForm: "No Parking Area",
    definition: "Zona totalmente vietata al parcheggio di mezzi e materiali. Delimitata dalla NPL. Nessuna eccezione.",
    category: "acronym",
    color: "bg-yellow-900/60 text-yellow-300",
  },
  {
    id: "gl-npl",
    term: "NPL",
    fullForm: "No Parking Line",
    definition: "Linea che delimita la NPA (No Parking Area). I veicoli non devono sostare oltre questa linea.",
    category: "acronym",
    color: "bg-yellow-800/60 text-yellow-300",
  },
  {
    id: "gl-twr",
    term: "TWR",
    fullForm: "Torre di Controllo (Tower)",
    definition: "Gestita da ENAV, coordina e istruisce il movimento di aeromobili e veicoli in Area di Manovra. I veicoli in Area di Manovra devono sempre avere contatto radio UHF con la TWR.",
    category: "acronym",
    color: "bg-teal-900/60 text-teal-300",
  },
  {
    id: "gl-fco",
    term: "FCO",
    fullForm: "Codice IATA – Aeroporto di Fiumicino (Roma)",
    definition: "Aeroporto Internazionale Leonardo da Vinci di Fiumicino. Addestramento pratico ADC-A iniziale: minimo 4 ore.",
    category: "acronym",
    color: "bg-emerald-900/60 text-emerald-300",
  },
  {
    id: "gl-cia",
    term: "CIA",
    fullForm: "Codice IATA – Aeroporto di Ciampino (Roma)",
    definition: "Aeroporto G.B. Pastine di Ciampino. Addestramento pratico ADC-A iniziale: minimo 2 ore.",
    category: "acronym",
    color: "bg-emerald-800/60 text-emerald-300",
  },
  {
    id: "gl-enac",
    term: "ENAC",
    fullForm: "Ente Nazionale per l'Aviazione Civile",
    definition: "Autorità italiana di regolazione tecnica, certificazione e vigilanza del settore dell'aviazione civile. I veicoli ENAC con luce gialla rotante hanno precedenza su tutti eccetto i mezzi di emergenza.",
    category: "acronym",
    color: "bg-indigo-900/60 text-indigo-300",
  },
  {
    id: "gl-enav",
    term: "ENAV",
    fullForm: "Ente Nazionale Assistenza al Volo",
    definition: "Gestisce il traffico aereo civile italiano. Tramite la Torre di Controllo (TWR) coordina il movimento di aeromobili e veicoli in Area di Manovra.",
    category: "acronym",
    color: "bg-cyan-900/60 text-cyan-300",
  },
  {
    id: "gl-adr",
    term: "ADR",
    fullForm: "Aeroporti di Roma",
    definition: "Società incaricata per legge di gestire le infrastrutture aeroportuali di FCO e CIA. Emette le ADC, gestisce la Sicurezza Operativa e i controlli Safety & Compliance.",
    category: "acronym",
    color: "bg-blue-800/60 text-blue-300",
  },
  {
    id: "gl-uhf",
    term: "UHF",
    fullForm: "Ultra High Frequency",
    definition: "Banda di frequenze radio (300 MHz – 3 GHz) usata per le comunicazioni con la TWR in Area di Manovra. Obbligatoria per i veicoli con ADC-M.",
    category: "acronym",
    color: "bg-teal-800/60 text-teal-300",
  },
  {
    id: "gl-uld",
    term: "ULD",
    fullForm: "Unit Load Device",
    definition: "Contenitore o pallet standardizzato usato per caricare bagagli e merci sugli aeromobili. I relativi carrelli hanno limiti precisi di traino e stoccaggio in Airside.",
    category: "acronym",
    color: "bg-amber-900/60 text-amber-300",
  },
  {
    id: "gl-obu",
    term: "OBU",
    fullForm: "On Board Unit",
    definition: "Dispositivo di localizzazione/sistema di bordo richiesto a Fiumicino per i mezzi azionati da motore secondo le D.d.S. aeroportuali.",
    category: "acronym",
    color: "bg-blue-900/60 text-blue-300",
  },
  {
    id: "gl-asmgcs",
    term: "A-SMGCS",
    fullForm: "Advanced Surface Movement Guidance and Control System",
    definition: "Sistema avanzato di guida e controllo del traffico di superficie aeroportuale. Alcuni mezzi devono essere equipaggiati con transponder dedicato per essere identificati dal sistema.",
    category: "acronym",
    color: "bg-cyan-900/60 text-cyan-300",
  },
  {
    id: "gl-aca",
    term: "ACA",
    fullForm: "Autorizzazione alla Circolazione in Airside",
    definition: "Documento autorizzativo del mezzo per la circolazione nelle aree aeroportuali interne. In specifici casi operativi deve essere conservato a bordo in originale.",
    category: "acronym",
    color: "bg-blue-950/70 text-blue-300",
  },
  {
    id: "gl-aid",
    term: "AID",
    fullForm: "Airside Information Display",
    definition: "Display informativo installato in prossimità dei varchi di accesso Airside, usato per fornire indicazioni operative e di safety agli utenti che entrano nelle aree interne.",
    category: "acronym",
    color: "bg-sky-900/60 text-sky-300",
  },
  {
    id: "gl-rwy",
    term: "RWY",
    fullForm: "Runway (pista di volo)",
    definition: "Pista di decollo e atterraggio. Fa parte dell'Area di Manovra. Accesso assolutamente vietato ai veicoli non autorizzati (segnaletica RWY STRIP NO ENTRY).",
    category: "acronym",
    color: "bg-green-900/60 text-green-300",
  },
  {
    id: "gl-eu",
    term: "EU 139/2014",
    fullForm: "Regolamento dell'Unione Europea n. 139/2014",
    definition: "Regolamento europeo che stabilisce i requisiti tecnici e le procedure amministrative per gli aeroporti civili. Uno dei tre pilastri normativi della circolazione in Airside (insieme al Manuale di Aeroporto e al Codice della Strada).",
    category: "acronym",
    color: "bg-sky-900/60 text-sky-300",
  },

  // ── AREE ──────────────────────────────────────────────────────────────────
  {
    id: "gl-airside",
    term: "Airside",
    definition: "Parte dell'aeroporto oltre i varchi di sicurezza e/o doganali, accessibile solo a personale autorizzato. Include piazzali, piste, veicolari e aree di sicurezza.",
    category: "area",
    color: "bg-sky-900/60 text-sky-300",
  },
  {
    id: "gl-landside",
    term: "Landside",
    definition: "Parte pubblica dell'aeroporto, accessibile senza controlli di sicurezza specifici. Include check-in, sale di attesa e parcheggi pubblici.",
    category: "area",
    color: "bg-slate-600/80 text-slate-300",
  },
  {
    id: "gl-viabilita",
    term: "Viabilità veicolare",
    definition: "Insieme delle veicolari o vie di scorrimento destinate al transito dei mezzi in Airside. Devono restare libere da soste, materiali e percorsi non autorizzati.",
    category: "area",
    color: "bg-slate-700/80 text-slate-300",
  },
  {
    id: "gl-area-manovra",
    term: "Area di Manovra",
    definition: "Parte dell'aeroporto adibita al decollo, atterraggio e movimento al suolo degli aeromobili. Comprende piste (RWY) e taxiway principali, ma NON i piazzali. Accesso richiede ADC-M e radio UHF.",
    category: "area",
    color: "bg-violet-900/60 text-violet-300",
  },
  {
    id: "gl-area-movimento",
    term: "Area di Movimento",
    definition: "Area di Manovra (piste + taxiway) + Piazzali (Apron). Termine più ampio che include tutto ciò che si muove in Airside. Ricorda: Movimento ⊃ Manovra.",
    category: "area",
    color: "bg-violet-800/60 text-violet-300",
  },
  {
    id: "gl-apron",
    term: "Apron (Piazzale)",
    definition: "Area predefinita per la sosta degli aeromobili, imbarco/sbarco passeggeri, carico/scarico merci, rifornimento e manutenzione. Non fa parte dell'Area di Manovra.",
    category: "area",
    color: "bg-emerald-900/60 text-emerald-300",
  },
  {
    id: "gl-stand",
    term: "Aircraft Stand (Piazzola)",
    definition: "Porzione specifica del piazzale per il parcheggio e l'assistenza di un singolo aeromobile. Contiene ERA, ESA ed è delimitata da ERL. Accesso solo con beacon spento e tacchi posizionati.",
    category: "area",
    color: "bg-green-900/60 text-green-300",
  },
  {
    id: "gl-taxiway",
    term: "Taxiway",
    definition: "Via di rullaggio: percorso definito destinato al movimento degli aeromobili a terra tra le diverse aree dell'aeroporto. Identificata dal centerline giallo. I veicoli attraversano solo alle intersezioni previste.",
    category: "area",
    color: "bg-green-800/60 text-green-300",
  },
  {
    id: "gl-rwy-strip",
    term: "Runway Strip",
    definition: "Striscia di sicurezza ai lati della pista di volo. Accesso assolutamente vietato ai veicoli non autorizzati (marcatura rossa RWY STRIP NO ENTRY).",
    category: "area",
    color: "bg-lime-900/60 text-lime-300",
  },

  // ── SEGNALETICA ──────────────────────────────────────────────────────────
  {
    id: "gl-centerline",
    term: "Centerline",
    definition: "Linea gialla continua al centro di una taxiway. Indica il percorso riservato agli aeromobili. I veicoli NON devono seguirla. Giallo = aeromobili; bianco = veicoli.",
    category: "marking",
    color: "bg-yellow-900/60 text-yellow-300",
  },
  {
    id: "gl-stop-aeronautico",
    term: "Stop Aeronautico",
    definition: "Segnaletica orizzontale e/o verticale che indica l'intersezione della viabilità veicolare con una taxiway. Obbligo di fermarsi completamente e verificare l'assenza di aeromobili in tutte le direzioni prima di attraversare.",
    category: "marking",
    color: "bg-red-900/60 text-red-300",
  },
  {
    id: "gl-zebratura-rossa",
    term: "Zebratura rossa",
    definition: "Marcatura orizzontale rossa sulla pavimentazione. Indica un'area completamente vietata alla sosta e al transito di qualsiasi veicolo o materiale.",
    category: "marking",
    color: "bg-red-800/60 text-red-300",
  },
  {
    id: "gl-conspicuous",
    term: "Conspicuous Color",
    definition: "Colorazione ad alta visibilità obbligatoria sui veicoli in Airside. Pannelli a scacchi rosso e bianco sui fianchi del veicolo per massimizzare la visibilità ai piloti in cabina e ai marshaller.",
    category: "marking",
    color: "bg-teal-900/60 text-teal-300",
  },

  // ── CONCETTI / ATTREZZATURE ────────────────────────────────────────────
  {
    id: "gl-beacon",
    term: "Beacon",
    definition: "Luce anticollisione rossa lampeggiante sull'aeromobile. ACCESO = aeromobile «vivo» (non avvicinarsi). SPENTO = aeromobile a terra (solo se anche i tacchi sono posizionati). Condizione necessaria per accedere in piazzola.",
    category: "concept",
    color: "bg-orange-900/60 text-orange-300",
  },
  {
    id: "gl-chocks",
    term: "Wheel Chocks (Tacchi)",
    definition: "Cunei posizionati alle ruote dell'aeromobile per impedirne il movimento involontario. Condizione necessaria (insieme al beacon spento) per accedere in piazzola.",
    category: "concept",
    color: "bg-orange-800/60 text-orange-300",
  },
  {
    id: "gl-jet-blast",
    term: "Jet Blast",
    definition: "Turbolenza violenta generata dai motori a reazione degli aeromobili. Può ribaltare veicoli leggeri e ferire il personale. Indicato da apposita segnaletica. Area di massimo rischio: dietro i motori durante l'avviamento.",
    category: "concept",
    color: "bg-rose-900/60 text-rose-300",
  },
  {
    id: "gl-marshaller",
    term: "Marshaller",
    definition: "Operatore qualificato che guida l'aeromobile a terra verso il parcheggio usando segnali visivi standardizzati (palette o bacchette luminose). Ha la precedenza assoluta nell'area di manovra della piazzola.",
    category: "concept",
    color: "bg-purple-900/60 text-purple-300",
  },
  {
    id: "gl-smoking-point",
    term: "Smoking Point",
    definition: "Unica area designata e sicura dove è consentito fumare in Airside. Fumare fuori da queste zone è vietato, anche a bordo dei veicoli.",
    category: "concept",
    color: "bg-slate-600/80 text-slate-300",
  },
  {
    id: "gl-qr-adr",
    term: "QR-code ADR",
    definition: "Adesivo obbligatorio sui veicoli in Airside (minimo 5×5 cm). Dà accesso rapido alle «Quick References» di Aeroporti di Roma. Non è consultabile durante la guida: solo a veicolo fermo.",
    category: "concept",
    color: "bg-blue-900/60 text-blue-300",
  },
  {
    id: "gl-grid-map",
    term: "Grid Map",
    definition: "Cartografia aeroportuale di bordo richiesta su alcuni mezzi. Deve essere disponibile nel formato previsto dalle disposizioni operative per consentire il rapido orientamento in area di manovra.",
    category: "concept",
    color: "bg-sky-900/60 text-sky-300",
  },
  {
    id: "gl-fap",
    term: "FAP",
    fullForm: "Filtro Anti Particolato",
    definition: "Dispositivo equivalente alla marmitta catalitica che, se presente sul veicolo, soddisfa il requisito che altrimenti richiederebbe il parafiamma interno.",
    category: "concept",
    color: "bg-slate-700/80 text-slate-300",
  },
  {
    id: "gl-turn-bar",
    term: "Turn Bar",
    definition: "Barra di virata sulla segnaletica di piazzola che indica al pilota il punto di inizio della manovra di virata in ingresso verso la posizione di sosta.",
    category: "marking",
    color: "bg-orange-900/60 text-orange-300",
  },
  {
    id: "gl-stand-id",
    term: "Stand ID",
    definition: "Marking identificativo della piazzola di sosta aeromobile. Riporta il codice dello stand e segue regole specifiche di posizionamento e colori di fondo e caratteri.",
    category: "marking",
    color: "bg-yellow-900/60 text-yellow-300",
  },
  {
    id: "gl-easa-type-c",
    term: "EASA Type C",
    definition: "Tipologia di luce ostacolo rossa installata sui mezzi aeroportuali. Va posizionata sulla sommità del mezzo, nella parte più visibile, con intensità minima prevista dalle disposizioni.",
    category: "concept",
    color: "bg-red-900/60 text-red-300",
  },

  // ── PROCEDURE ─────────────────────────────────────────────────────────────
  {
    id: "gl-recurrent",
    term: "Recurrent Training",
    definition: "Aggiornamento periodico obbligatorio ogni 24 mesi per mantenere la validità dell'ADC-A. Si svolge in modalità e-learning. La mancata effettuazione obbliga il datore di lavoro a inibire la guida.",
    category: "procedure",
    color: "bg-violet-900/60 text-violet-300",
  },
  {
    id: "gl-refresher",
    term: "Refresher Training",
    definition: "Ripasso pratico obbligatorio (2 ore FCO, 1 ora CIA) richiesto dopo un'interruzione della guida in Airside compresa tra 3 e 12 mesi consecutivi. Supervisione da ADE.",
    category: "procedure",
    color: "bg-violet-800/60 text-violet-300",
  },
  {
    id: "gl-remedial",
    term: "Remedial Training",
    definition: "Percorso correttivo disposto dal Safety Manager quando viene rilevata una criticità operativa o comportamentale. Prevede un follow-up obbligatorio dopo tre mesi.",
    category: "procedure",
    color: "bg-rose-900/60 text-rose-300",
  },
  {
    id: "gl-passo-duomo",
    term: "Passo d'uomo",
    definition: "Velocità di camminata di un adulto, circa 4-5 km/h. È la velocità raccomandata all'interno delle piazzole aeromobili, dove la presenza di personale e attrezzature impone la massima cautela.",
    category: "procedure",
    color: "bg-amber-900/60 text-amber-300",
  },
  {
    id: "gl-fod-walk",
    term: "FOD Walk",
    definition: "Ispezione periodica a piedi del piazzale e delle aree di movimento per identificare e rimuovere oggetti estranei (FOD). Procedura preventiva danni agli aeromobili.",
    category: "procedure",
    color: "bg-amber-800/60 text-amber-300",
  },
];

// ── Category labels ────────────────────────────────────────────────────────
export const CATEGORY_LABELS: Record<GlossaryCategory, string> = {
  acronym: "Acronimo",
  area: "Area",
  marking: "Segnaletica",
  concept: "Concetto",
  procedure: "Procedura",
};
